import type { Metadata } from 'next'
import SideBar from '@/components/SideBar/Sidebar'
import '../styles/globals.scss'

export const metadata: Metadata = {
  title: 'Ecommerce Test',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='custom-cms'>
        <SideBar />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
